### ISSUE TITLE
error sizes

### ISSUE THREAD

**Issue by AdrianRamos15** [CristianRubio4/-2022-ISO2-C04-ET.01#7]

**Comment by CristianRubio4** [comment]
- Solucion linea 9 y 10
![image](https://user-images.githubusercontent.com/114807919/209340883-534edfdd-8952-445b-b608-44523d03cfad.png)
 
- Solucion linea 22 y 32
![image](https://user-images.githubusercontent.com/114807919/209340766-d3ce18bd-aaa5-4f9a-8820-b3ff1380125c.png)

- Solucion linea 42 
![image](https://user-images.githubusercontent.com/114807919/209340928-4d9a3fba-ceae-42ec-b233-e7bd6a2808a4.png)
