### ISSUE TITLE
error whitespace

### ISSUE THREAD

**Issue by AdrianRamos15** [CristianRubio4/-2022-ISO2-C04-ET.01#8]

**Comment by CristianRubio4** [comment]
- Solucion lineas 5 y 11
![image](https://user-images.githubusercontent.com/114807919/209342353-5f79fbab-7d1d-42c8-a0e8-27510ce64322.png)
- Solucion lineas 22 y 33
![image](https://user-images.githubusercontent.com/114807919/209342469-49fb519f-8a61-4788-a25a-d5c476d41718.png)
- Solucion linea 51
![image](https://user-images.githubusercontent.com/114807919/209342522-570bbaad-ebc8-42b5-8d23-b2e9274ee57c.png)
